package main

// MockPhones represents a map of mock phone data
var MockPhones = []map[string]interface{}{
	{
		"productName":      "Samsung Galaxy S23",
		"manufacturer":     "Samsung",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1080,
		"screenHeightPx":   2340,
		"nativePlatform":   "Android",
		"screenDensityDpi": 420,
		"glEsVersion":      32,
		"cpuModel":         "Snapdragon 8 Gen 2",
		"cpuMake":          "Qualcomm",
		"ramMb":            8192,
	},
	{
		"productName":      "Google Pixel 7",
		"manufacturer":     "Google",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1080,
		"screenHeightPx":   2400,
		"nativePlatform":   "Android",
		"screenDensityDpi": 440,
		"glEsVersion":      32,
		"cpuModel":         "Google Tensor G2",
		"cpuMake":          "Google",
		"ramMb":            8192,
	},
	{
		"productName":      "OnePlus 11",
		"manufacturer":     "OnePlus",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1440,
		"screenHeightPx":   3216,
		"nativePlatform":   "Android",
		"screenDensityDpi": 565,
		"glEsVersion":      32,
		"cpuModel":         "Snapdragon 8 Gen 2",
		"cpuMake":          "Qualcomm",
		"ramMb":            16384,
	},
	{
		"productName":      "Xiaomi 13",
		"manufacturer":     "Xiaomi",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1080,
		"screenHeightPx":   2400,
		"nativePlatform":   "Android",
		"screenDensityDpi": 440,
		"glEsVersion":      31,
		"cpuModel":         "Snapdragon 8 Gen 2",
		"cpuMake":          "Qualcomm",
		"ramMb":            8192,
	},
	{
		"productName":      "Motorola Edge 30 Pro",
		"manufacturer":     "Motorola",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1080,
		"screenHeightPx":   2400,
		"nativePlatform":   "Android",
		"screenDensityDpi": 400,
		"glEsVersion":      32,
		"cpuModel":         "Snapdragon 8 Gen 1",
		"cpuMake":          "Qualcomm",
		"ramMb":            12288,
	},
	{
		"productName":      "Sony Xperia 1 IV",
		"manufacturer":     "Sony",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1644,
		"screenHeightPx":   3840,
		"nativePlatform":   "Android",
		"screenDensityDpi": 643,
		"glEsVersion":      32,
		"cpuModel":         "Snapdragon 8 Gen 1",
		"cpuMake":          "Qualcomm",
		"ramMb":            12288,
	},
	{
		"productName":      "Nokia G60 5G",
		"manufacturer":     "Nokia",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1080,
		"screenHeightPx":   2400,
		"nativePlatform":   "Android",
		"screenDensityDpi": 400,
		"glEsVersion":      30,
		"cpuModel":         "Snapdragon 695 5G",
		"cpuMake":          "Qualcomm",
		"ramMb":            4096,
	},
	{
		"productName":      "Realme GT 2 Pro",
		"manufacturer":     "Realme",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1440,
		"screenHeightPx":   3216,
		"nativePlatform":   "Android",
		"screenDensityDpi": 560,
		"glEsVersion":      32,
		"cpuModel":         "Snapdragon 8 Gen 1",
		"cpuMake":          "Qualcomm",
		"ramMb":            8192,
	},
	{
		"productName":      "Oppo Find X5 Pro",
		"manufacturer":     "Oppo",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1440,
		"screenHeightPx":   3216,
		"nativePlatform":   "Android",
		"screenDensityDpi": 525,
		"glEsVersion":      32,
		"cpuModel":         "Snapdragon 8 Gen 1",
		"cpuMake":          "Qualcomm",
		"ramMb":            12288,
	},
	{
		"productName":      "Vivo X80 Pro",
		"manufacturer":     "Vivo",
		"deviceClass":      "PHONE",
		"screenWidthPx":    1440,
		"screenHeightPx":   3200,
		"nativePlatform":   "Android",
		"screenDensityDpi": 515,
		"glEsVersion":      32,
		"cpuModel":         "Snapdragon 8 Gen 1",
		"cpuMake":          "Qualcomm",
		"ramMb":            12288,
	},
}
